# Generated by Django 5.2.7 on 2026-02-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_rename_full_name_mechanic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='mechanic',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
